### PR TITLE
change to prevent crash on add

### PR DESCRIPTION
**Pull request by automaticgiant**
It at least stops it from crashing. Windows still says cannot connect to the printer. Idk what the code does well enough for something better. Here's a starting point. Let's not merge this yet, but start a conversation. Let's fix this (#1).

### CODE REVIEW

**Comment by automaticgiant** [comment]
Probably should add a regression test for this once requests are captured.

**Comment by watson** [comment]
@automaticgiant thanks for the PR :)

Unfortunately this would make the current way of testing for the presence of the `requested-attributes` tag fail:
https://github.com/watson/ipp-printer/blob/b285e58b78034d588c2a3acd897b471df2b23268/lib/operations.js#L68

Instead I would think the caller of `utils.requestedAttributes` should check if the function returns something and act accordingly. I'm currently working on an update that implements this.

**Comment by automaticgiant** [comment]
Yeah - I'm only vaguely familiar with IPP and am not up for studying it and your code yet(only budgeted quick and easy hack amount of time for this project), but maybe if you could document the dataflow your library supports a little better and take a look at the Windows client conversation and put some notes about that in relation to typical flow, I could take another swing at it.
Works great for cups clients though!

**Comment by watson** [comment]
Once again thanks for the pull request - your contributions and feedback is highly appreciated :smiley:  I've fixed the issue you encountered in a different way then you proposed here (released in v0.3.1), so I will go ahead and close this PR now. I hope though that this doesn't deter you from making pull requests in the future.

**Comment by watson** [comment]
p.s. good idea with some more documentation on the dataflow. I think I'll work on creating it as I implement the different operations from the RFC

**Pull request closed without merging**
